---
title: "Lab4"
author: daria.toikina@yandex.ru
date: "2025-11-17"
format: md
output-file: README.md
editor: 
  markdown: 
    wrap: 72
---

# Цель работы

1\. Зекрепить практические навыки использования языка программирования R
для обработки данных

2\. Закрепить знания основных функций обработки данных экосистемы
tidyverse языка R

3\. Закрепить навыки исследования метаданных DNS трафика

# Задание

Используя программный пакет dplyr, освоить анализ DNS логов с помощью
языка программирования R.

## Подготовка

### Установка необходимых библеотек

```         
> library(tidyselect)
> library(httr)
> library(jsonlite)
> library(stringi)
```

### Загрузка данных

```         
url <- "https://storage.yandexcloud.net/dataset.ctfsec/dns.zip"
> download.file(url, "dns.zip")
trying URL 'https://storage.yandexcloud.net/dataset.ctfsec/dns.zip'
Content type 'application/zip' length 6407934 bytes (6.1 MB)
==================================================
downloaded 6.1 MB
```

### Добавьте пропущенные данные о структуре данных (назначении столбцов)

```         
col_names <- c("ts", "uid", "id.orig_h", "id.orig_p", "id.resp_h","id.resp_p", "proto", "trans_id", "rtt", "query",  "qclass", "qclass_name", "qtype", "qtype_name",  "rcode", "rcode_name", "AA", "TC", "RD", "RA", "Z", "answers", "TTLs", "rejected")
> names(dns_data) <- col_names[1:ncol(dns_data)]
```

### Преобразуйте данные в столбцах в нужный формат

```         
dns_data <- dns_data %>% mutate( ts = as.POSIXct(ts, origin = "1970-01-01"), id.orig_p = as.integer(id.orig_p), id.resp_p = as.integer(id.resp_p), rtt = as.numeric(rtt) )
```

### Просмотрите общую структуру данных с помощью функции glimpse()

```         
dns_data %>% glimpse()
Rows: 320,840
Columns: 23
$ ts          <dttm> 2012-03-16 16:30:05, 2012-03-16 16:30:15, 2012-03-16 16:30:15, 2012-03-16 16:30:16, 2012-03…
$ uid         <chr> "CWGtK431H9XuaTN4fi", "C36a282Jljz7BsbGH", "C36a282Jljz7BsbGH", "C36a282Jljz7BsbGH", "C36a28…
$ id.orig_h   <chr> "192.168.202.100", "192.168.202.76", "192.168.202.76", "192.168.202.76", "192.168.202.76", "…
$ id.orig_p   <int> 45658, 137, 137, 137, 137, 137, 137, 137, 137, 137, 137, 137, 137, 45658, 45659, 45658, 137,…
$ id.resp_h   <chr> "192.168.27.203", "192.168.202.255", "192.168.202.255", "192.168.202.255", "192.168.202.255"…
$ id.resp_p   <int> 137, 137, 137, 137, 137, 137, 137, 137, 137, 137, 137, 137, 137, 5353, 5353, 137, 137, 137, …
$ proto       <chr> "udp", "udp", "udp", "udp", "udp", "udp", "udp", "udp", "udp", "udp", "udp", "udp", "udp", "…
$ trans_id    <int> 33008, 57402, 57402, 57402, 57398, 57398, 57398, 62187, 62187, 62187, 62190, 62190, 62190, 0…
$ rtt         <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …
$ query       <chr> "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1…
$ qclass      <chr> "C_INTERNET", "C_INTERNET", "C_INTERNET", "C_INTERNET", "C_INTERNET", "C_INTERNET", "C_INTER…
$ qclass_name <chr> "33", "32", "32", "32", "32", "32", "32", "32", "32", "32", "33", "33", "33", "12", "12", "3…
$ qtype       <chr> "SRV", "NB", "NB", "NB", "NB", "NB", "NB", "NB", "NB", "NB", "SRV", "SRV", "SRV", "PTR", "PT…
$ qtype_name  <chr> "0", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "0", "-", "-", "-…
$ rcode       <chr> "NOERROR", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "NOERROR", …
$ rcode_name  <lgl> FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, F…
$ AA          <lgl> FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, F…
$ TC          <lgl> FALSE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, FALSE, FALSE, FALSE, FAL…
$ RD          <lgl> FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, F…
$ RA          <int> 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…
$ Z           <chr> "-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-…
$ answers     <chr> "-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-…
$ TTLs        <lgl> FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, F…
> 
```

## Анализ

### Сколько участников информационного обмена в сети Доброй Организации?

```         
> total_participants <- dns_data %>% select(id.orig_h, id.resp_h) %>% unlist() %>% unique() %>% length()
> print(paste("Всего участников информационного обмена:", total_participants))
[1] "Всего участников информационного обмена: 1288"
```

### Какое соотношение участников обмена внутри сети и участников обращений к внешним ресурсам?

#### Все уникальные IP

```  
all_ips <- dns_data %>% select(id.orig_h, id.resp_h) %>% unlist() %>% unique()
```

#### Внутренние IP 

```         
internal_ips <- all_ips[grepl("^192\\.168\\.|^10\\.|^172\\.", all_ips)]
```

#### Внешние IP

```         
external_ips <- setdiff(all_ips, internal_ips)
```

#### Вывод

```         
> print(paste("Внутренних участников:", internal_count))
[1] "Внутренних участников: 1211"
> print(paste("Внешних участников:", external_count))
[1] "Внешних участников: 77"
> print(paste("Соотношение внутренних/внешних:", round(internal_count/external_count, 2)))
[1] "Соотношение внутренних/внешних: 15.73"
```

### Найдите топ-10 участников сети, проявляющих наибольшую сетевую активность.
```
> top_active_ips <- dns_data %>% count(id.orig_h, sort = TRUE) %>% head(10)
> print("Топ-10 самых активных участников:")
[1] "Топ-10 самых активных участников:"
> top_active_ips %>% print()
         id.orig_h     n
1    10.10.117.210 75943
2   192.168.202.93 15725
3    10.10.117.209 14222
4   192.168.202.97 14216
5  192.168.202.110 13372
6  192.168.202.103 12818
7   192.168.203.63 11962
8   192.168.202.76 10950
9  192.168.229.252  9530
10  192.168.202.83  9165
```

### Найдите топ-10 доменов, к которым обращаются пользователи сети и соответственное количество обращений
```
top_domains <- dns_data %>% filter(!is.na(query), query != "") %>% count(query, sort = TRUE) %>%  head(10)
> print("Топ-10 доменов по количеству обращений:")
[1] "Топ-10 доменов по количеству обращений:"
> top_domains %>% print()
  query      n
1     1 317087
2     -   2483
3     3    824
4 32769    446
```

### Опеределите базовые статистические характеристики (функция summary() ) интервала времени между последовательными обращениями к топ-10 доменам.
```
>analyze_time_intervals <- function(domain_name) { dns_data %>% filter(query == domain_name) %>% arrange(ts) %>% mutate(time_diff = as.numeric(ts - lag(ts))) %>%  pull(time_diff) %>% .[!is.na(.)] %>% summary() }
> top_domains_list <- top_domains %>% pull(query)
print("Статистика интервалов времени для топ-10 доменов:")
[1] "Статистика интервалов времени для топ-10 доменов:"
> for(domain in top_domains_list) {
+     print(paste("Домен:", domain))
+     analyze_time_intervals(domain) %>% print()
+     cat("\n")
+ }
[1] "Домен: 1"
     Min.   1st Qu.    Median      Mean   3rd Qu.      Max. 
    0.000     0.000     0.010     0.278     0.120 49669.280 

[1] "Домен: -"
     Min.   1st Qu.    Median      Mean   3rd Qu.      Max. 
    0.000     0.010     0.655    35.546     2.890 49786.850 

[1] "Домен: 3"
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
   0.00    0.00    0.01   39.45    1.02 7115.93 

[1] "Домен: 32769"
    Min.  1st Qu.   Median     Mean  3rd Qu.     Max. 
    0.00     0.06     1.65   195.15     2.21 52833.48 
```

### Часто вредоносное программное обеспечение использует DNS канал в качестве канала управления, периодически отправляя запросы на подконтрольный злоумышленникам DNS сервер. По периодическим запросам на один и тот же домен можно выявить скрытый DNS канал. Есть ли такие IP адреса в исследуемом датасете?
```

> suspicious_dns <- dns_data %>%
+     filter(!is.na(query), query != "", query != "1", query != "-") %>%
+     group_by(id.orig_h, query) %>%
+     summarise(
+         request_count = n(),
+         first_request = min(ts),
+         last_request = max(ts),
+         time_span = as.numeric(max(ts) - min(ts)),
+         avg_interval = ifelse(request_count > 1, time_span / (request_count - 1), NA),
+         .groups = 'drop'
+     ) %>%
+     filter(request_count >= 3, 
+            !is.na(avg_interval), 
+            avg_interval > 0) %>%
+     arrange(avg_interval)
> 
> print("9. Анализ на скрытые DNS-каналы:")
[1] "9. Анализ на скрытые DNS-каналы:"
> if(nrow(suspicious_dns) > 0) {
+     print("Обнаружены подозрительные паттерны:")
+     suspicious_dns %>% print()
+ } else {
+     print("Явных признаков скрытых DNS-каналов не обнаружено")
+ }
[1] "Обнаружены подозрительные паттерны:"
# A tibble: 17 × 7
   id.orig_h                    query request_count first_request       last_request        time_span avg_interval
   <chr>                        <chr>         <int> <dttm>              <dttm>                  <dbl>        <dbl>
 1 192.168.202.110              32769           406 2012-03-16 17:19:02 2012-03-16 22:45:43      5.44       0.0134
 2 192.168.202.110              3               111 2012-03-16 17:11:53 2012-03-16 22:33:56      5.37       0.0488
 3 192.168.202.102              3               515 2012-03-16 17:02:00 2012-03-16 17:45:46     43.8        0.0852
 4 2001:dbb:c18:202:20c:29ff:f… 3                11 2012-03-16 22:46:05 2012-03-16 22:47:13      1.13       0.113 
 5 192.168.204.45               3                65 2012-03-16 17:23:54 2012-03-17 01:45:40      8.36       0.131 
 6 192.168.202.4                3                12 2012-03-16 23:37:08 2012-03-16 23:39:59      2.84       0.258 
 7 192.168.202.108              3                76 2012-03-16 18:51:26 2012-03-16 19:11:36     20.2        0.269 
 8 192.168.202.79               3                16 2012-03-16 16:44:32 2012-03-16 22:15:40      5.52       0.368 
 9 fe80::c62c:3ff:fe37:efc      32769             8 2012-03-16 16:59:06 2012-03-16 23:57:40      6.98       0.997 
10 fe80::ba8d:12ff:fe53:a8d8    32769             8 2012-03-16 16:47:50 2012-03-17 00:15:35      7.46       1.07  
11 fe80::3e07:54ff:fe1c:a665    32769             3 2012-03-16 22:18:22 2012-03-17 01:03:39      2.75       1.38  
12 fe80::3e07:54ff:fe41:3ed3    32769             6 2012-03-16 17:20:03 2012-03-17 16:42:35     23.4        4.68  
13 fe80::62fb:42ff:feef:5440    32769             5 2012-03-16 20:16:37 2012-03-17 16:55:12     20.6        5.16  
14 192.168.202.83               3                 4 2012-03-16 23:12:54 2012-03-16 23:37:07     24.2        8.07  
15 192.168.202.80               3                 4 2012-03-16 18:50:37 2012-03-16 18:51:20     43.5       14.5   
16 192.168.203.45               3                 4 2012-03-16 17:09:42 2012-03-16 17:10:33     51.6       17.2   
17 192.168.202.94               3                 4 2012-03-16 17:40:11 2012-03-16 17:41:06     55.7       18.6   
```

### Определите местоположение (страну, город) и организацию-провайдера для топ-10 доменов. Для этого можно использовать сторонние сервисы, например http://ip-api.com (API-ндпоинт –http:/ /ip-api.com/json).
```
get_geo_info <- function(ip) {
+     tryCatch({
+         response <- GET(paste0("http://ip-api.com/json/", ip))
+         if (status_code(response) == 200) {
+             info <- content(response, "parsed")
+             return(tibble(
+                 ip = ip,
+                 country = ifelse(!is.null(info$country), info$country, NA),
+                 city = ifelse(!is.null(info$city), info$city, NA),
+                 isp = ifelse(!is.null(info$isp), info$isp, NA),
+                 org = ifelse(!is.null(info$org), info$org, NA)
+             ))
+         }
+     }, error = function(e) NULL)
+     return(NULL)
+ }
> external_ips_for_geo <- dns_data %>%
+     filter(!grepl("^192\\.168\\.|^10\\.|^172\\.|^fe80::", id.resp_h),
+            id.resp_h != "ff02::1:3",
+            id.resp_h != "-") %>%
+     distinct(id.resp_h) %>%
+     head(5)
> print("10. Геолокация для внешних IP адресов:")
[1] "10. Геолокация для внешних IP адресов:"
> print(paste("Найдено внешних IP:", length(external_ips_for_geo)))
[1] "Найдено внешних IP: 1"
> 
> if(length(external_ips_for_geo) > 0) {
+     geo_results <- map_df(external_ips_for_geo, get_geo_info)
+     
+     if(nrow(geo_results) > 0) {
+         print("Геолокационная информация:")
+         geo_results %>% print()
+     } else {
+         print("Не удалось получить геолокационную информацию")
+     }
+ } else {
+     print("Внешние IP для геолокации не найдены")
+ }
[1] "Не удалось получить геолокационную информацию"
```